### ISSUE TITLE
This repo should ideally be a transfer rather than a fork

### ISSUE THREAD

**Issue by tom-seddon** [stardot/beebasm#1]
Sorry, didn't know how to make this nicely visible otherwise :)

I'll transfer the beebasm repo over to stardot - as far as I can tell, this maintains a link from tom-seddon/beebasm to stardot/beebasm. This cuts down on fork count and nobody need then update their working copy: https://help.github.com/articles/about-repository-transfers/

Please reply when you read this, and I'll delete the repo and do the transfer!

--Tom

**Comment by tom-seddon** [comment]
Oops... looks like somebody else (Kieran?) will have to delete the repo, as I don't seem to have the rights!

--Tom

**Comment by tom-seddon** [comment]
Actually - no, I'm completely wrong about this, because that would mean I wouldn't then be able to fork my own copy back from stardot/beebasm - since it looks as if the forwarding relies on the original owner no longer having a repo by that name.

So I'm closing this issue, and I think it's fine as it stands. I'll try to figure out how you get rid of the 'forked from...' thing, since stardot/beebasm should really be the authoritative copy.

--Tom

**Comment by simondotm** [comment]
You can reassign new owners to a repo for a clean move with no forks etc

**Comment by simondotm** [comment]
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/
