### ISSUE TITLE
Convert about.txt to README.md

### ISSUE THREAD

**Issue by simondotm** [stardot/beebasm#28]
Having a README.md version of the info file is more GitHub friendly.
I've checked one into the proposed-updates branch, since I noticed there had been updates to the about.txt file there.

We should probably remove the about.txt file in due course so that there's only one information file to maintain?

**Comment by ZornsLemma** [comment]
Thanks, this looks great! I think we should remove about.txt ASAP; it's just going to cause confusion to have both lying around.

**Comment by simondotm** [comment]
Agreed. Shall I go ahead an do that or do you want to take care of it?

**Comment by ZornsLemma** [comment]
I've removed about.txt now; I'll leave you to close this issue if it looks good to you.
