### ISSUE TITLE
Basic tokeniser crashes last line isn't blank

### ISSUE THREAD

**Issue by davidgiven** [stardot/beebasm#30]
If you use PUTBASIC on a file where the last line doesn't end in a line feed, then beebasm seg faults.

...there's not really a lot more useful I can say; it seems completely reproducible!

This is with head of git as of writing.

**Comment by mungre** [comment]
I created a really simple basic file with a dangling last line... and of course it worked fine.

Can you post an example?

**Comment by davidgiven** [comment]
Huh.

...so it only seems to happen when outputting to an SSD. I attach a turnkey example, which I should totally have done in the first place --- sorry:

[test.zip](https://github.com/stardot/beebasm/files/2041814/test.zip)

Do:

    beebasm -i test.asm -do test.ssd

...to run.

**Comment by mungre** [comment]
I reproduced it in Windows 10's Ubuntu environment.  There's a fix (I hope!) in the proposed-updates branch: https://github.com/stardot/beebasm/tree/proposed-updates

**Comment by davidgiven** [comment]
Good to know --- belatedly, I'm on amd64 Debian.

**Comment by davidgiven** [comment]
Incidentally, so it doesn't get lost; from #32:

Line 757 of BASIC.cpp, which eats whitespace, doesn't check for EOF, so if there are _two_ blank lines at the end of the file it eats forever until it overruns the buffer and then crashes.

**Comment by mungre** [comment]
Fixed in proposed-updates: https://github.com/stardot/beebasm/commit/3ee1e6a865a1d8af664016cee5c1e21f1601f484
