### ISSUE TITLE
COPYBLOCK isn't in the documentation

### ISSUE THREAD

**Issue by davidgiven** [stardot/beebasm#31]
I only found out about it from the changelog!

I'd suggest:

---snip---
COPYBLOCK <start addr>, <end addr>, <dest addr>

This copies a block of assembled data from one location to another. This is useful for allowing code assembled at one location to be copied into a program's data area (for relocation later).
---snip---

**Comment by mungre** [comment]
Fixed in proposed-updates: https://github.com/stardot/beebasm/commit/beef190f0ef4af8e66a2e06ea11725d615ce77cd

**Comment by davidgiven** [comment]
Thanks!
