### ISSUE TITLE
Allow string arguments to macros

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/beebasm#33]
Suggested by davidgiven in passing in https://github.com/stardot/beebasm/issues/32. This might or might not be best done as part of adding string support in other ways (e.g. the ability to have string variables); I haven't thought about this in any detail, just raising this issue to track the idea.

**Comment by cardboardguru76** [comment]
This would be good. Allowing the same macro to be used with various addressing modes simply by passing a full operand string rather than just a number.
