### ISSUE TITLE
Add -writes option to set number of disc writes in ssd catalogue

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/beebasm#39]
tricky has implemented this and I've put the code on a branch here: https://github.com/ZornsLemma/beebasm/tree/tricky-writes

**Comment by chriskillpack** [comment]
I don't see anything controversial that would prevent it from going into the next beebasm release, though error checking on command line option values is inconsistent. It is acceptable to me that an invalid numeric value would set disk writes to 0, the default value without the `-writes` option.

Want to make a PR against `proposed-updates` so we can get it in?

**Comment by ZornsLemma** [comment]
Done! I haven't tweaked the validation, do you want me to take a look at that (I probably can't do it tonight though)? I'm quite happy for you to do it, of course!

**Comment by chriskillpack** [comment]
IMO missing validation isn't a blocker on this feature since we are missing validation on other command line options. We should address in a follow up PR.

**Comment by ZornsLemma** [comment]
See discussion on pull request #72, it looks like this was merged to proposed-updates a while ago and I forgot to note it here.

**Comment by mungre** [comment]
This is in release v1.10 as the "-cycle" option.
