### ISSUE TITLE
Allow -help on command line as well as --help

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/beebasm#40]
All other beebasm options use a single '-' prefix and it annoys me a little bit to have beebasm tell me to use a double '-' prefix when I accidentally do 'beebasm -help'. I think we should support both. I'm happy to implement this if there are no objections.

**Comment by ZornsLemma** [comment]
I've just committed this change to proposed-updates.

**Comment by mungre** [comment]
Fixed in v1.10
