### ISSUE TITLE
Add -dd option which dumps labels with nested scopes

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/beebasm#42]
tricky has written the code for this and I've put it on github here: https://github.com/ZornsLemma/beebasm/commits/tricky-label-export

This is like -d, but shows the structure of the nested scopes in the label names. See the discussion in the stardot subthread starting here: https://stardot.org.uk/forums/viewtopic.php?f=55&t=12199&start=60#p263715

**Comment by mungre** [comment]
This is in release v1.10.
