### ISSUE TITLE
PUTBASIC doesn't correctly tokenise PAGE in all cases

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/beebasm#45]
It does work in a lot of cases, but not all. The attached [page.zip](https://github.com/stardot/beebasm/files/5277882/page.zip) shows two problematic cases and can be built with:
```
beebasm -i page.6502 -do page.ssd
```
Here's a screenshot from b-em showing the problem, note that after the first error I delete line 1 and it then gives an error in line 5.
![Screenshot at 2020-09-24 18-02-29](https://user-images.githubusercontent.com/7988240/94176795-88145100-fe90-11ea-9085-c302ab0a86e3.png)

**Comment by ZornsLemma** [comment]
The above was a bit vague as to what does and doesn't work; here's a modified page2.zip which shows that PAGE does sometimes work on the right hand side of "=" .
[page2.zip](https://github.com/stardot/beebasm/files/6255176/page2.zip)
![Screenshot at 2021-04-04 20-00-17](https://user-images.githubusercontent.com/7988240/113518826-94384400-9580-11eb-8b1b-0f304045f0d8.png)

**Comment by ZornsLemma** [comment]
I think I now have a fix for this on https://github.com/ZornsLemma/beebasm/tree/rhs-token-fix. Thanks to Richard Russell (https://stardot.org.uk/forums/viewtopic.php?f=55&t=22210) for suggesting the underlying problem (https://stardot.org.uk/forums/viewtopic.php?f=55&t=22210)!

**Comment by ZornsLemma** [comment]
I've merged this fix to proposed-updates.

**Comment by mungre** [comment]
Fixed in v1.10 and there's a test for it.
