### ISSUE TITLE
MSVCP100.dll missing from Windows 10, need to install Microsoft Visual C++ 2010 Redistributable Package (x86)

### ISSUE THREAD

**Issue by evoncken** [stardot/beebasm#46]
Problem:
* After copying beebasm.exe into the %PATH%, the assembler still did not work from VS Code (no output).
   Running it from a command prompt in Windows 10 shows that MSVCP100.dll was missing.

Solution:
* Install the 32-bit Microsoft Visual C++ 2010 Redistributable Package (x86) - downloaded as vcredist_x86.exe.
   Now, beebasm.exe works as expected. Suggest adding this information to the README?

**Comment by mungre** [comment]
beebasm.exe is created on github now using an up-to-date compiler.  Recent versions of the compiler all use the same redistributable package and Windows Update should keep it current, so this error should be a thing of the past.

**Comment by mungre** [comment]
My mistake, if you do a fresh install of Windows you won't have the files.  I've added a note to the README.
