### ISSUE TITLE
$ for Hex and % for Binary  missing from documentation

### ISSUE THREAD

**Issue by cardboardguru76** [stardot/beebasm#47]
These are mentioned in the change log. However they are missing from the main body of the documentation.
                  Added '$' as a valid hex literal prefix.
                  Added '%' as a binary literal prefix.
                  
Probably worth going through all of the changelog and checking for new features to see if they are documented.

**Comment by ZornsLemma** [comment]
Thanks, I've added this to README.md on the proposed-updates branch. I've had a quick look over the changelog and I can't see anything else missing; if you spot anything else please let me know!

**Comment by mungre** [comment]
Fixed in v1.10.
