### ISSUE TITLE
Allow underscore in numeric literals

### ISSUE THREAD

**Issue by cardboardguru76** [stardot/beebasm#48]
Some assemblers and compilers allow the splitting up of numbers with underscores that are ignored. It's particularly useful for splitting up bitfields in binary literals. But could be used with decimal and hex too.

e.g:

.byteWithBitfields EQUB %001_11010
.wordWithButfields EQUB %1101_1001_0101_0101
.whyNot EQUB &F_0FF

**Comment by mungre** [comment]
Fixed in v1.10.
