### ISSUE TITLE
Directive to switch on or off the verbose output.

### ISSUE THREAD

**Issue by cardboardguru76** [stardot/beebasm#50]
It would be nice to have verbose output for actual code. But switch it off where there are large chunks of data, e.g. sprite tables, or perhaps included libraries that are not under current development.

In the BASIC assembler you can switch output off and on as often as you like with OPT in the code. But with Beebasm, it's an all or nothing choice baed on a command line switch.

**Comment by mungre** [comment]
Fixed in v1.10.
