### ISSUE TITLE
1.10rc2: -D SYMBOL fails with default or negative value

### ISSUE THREAD

**Issue by regregex** [stardot/beebasm#83]
1.10rc2 is not accepting a symbol definition from the command line without an explicit, non-negative value. 1.09 is known good.  `README.md` defines the default value of symbol definitions to be -1, and both default and explicit definitions are rejected: 

    $ beebasm --help
    beebasm 1.10rc2
    ...
    
    $ beebasm -i edos.6502 -D _O2791S -D _SWRAM
    Invalid -D expression: _O2791S
    
    $ beebasm -i edos.6502 -D _O2791S=-1 -D _SWRAM
    Invalid -D expression: _O2791S=-1
    
    $ beebasm -i edos.6502 -D _O2791S=1 -D _SWRAM
    Invalid -D expression: _SWRAM
    
    $ beebasm -i edos.6502 -D _O2791S=1 -D _SWRAM=1
    To coupon =&3746  Code size =&37FD

**Comment by mungre** [comment]
Oops!  Thanks for the report.  This is fixed by #84.

**Comment by regregex** [comment]
Woah, was about to submit a fix but you beat me to it! Great work, thanks.
